RELEASE_ID="nxp-6.18.2-1.0.0"
STATUS="experimental"
NXP_BSP_VERSION="6.18.2-1.0.0"
YOCTO_SERIES="whinlatter"
BUILD_DIR="build-development-nxp-6.18.2-1.0.0"
IMAGE="geisa-dev-image"
DISTRO="geisa-dev"
SOURCE_IDS="base bitbake openembedded-core meta-yocto meta-arm meta-freescale meta-freescale-distro meta-freescale-ml meta-imx meta-openembedded meta-virtualization meta-clang"
LAYER_PATHS="sources/meta-freescale-distro sources/meta-freescale-ml sources/meta-imx/meta-imx-bsp sources/meta-imx/meta-imx-ml sources/meta-imx/meta-imx-sdk sources/meta-openembedded/meta-oe sources/meta-openembedded/meta-python sources/meta-openembedded/meta-networking sources/meta-openembedded/meta-filesystems sources/meta-openembedded/meta-multimedia sources/meta-openembedded/meta-gnome sources/meta-openembedded/meta-webserver sources/meta-openembedded/meta-perl sources/meta-virtualization sources/meta-clang"
BBMASK_PATHS=""
MACHINE_IMX93="geisa-imx93"
MACHINE_IMX95="geisa-imx95"
GEISA_NXP_MACHINE_INCLUDE_IMX93="conf/machine/imx93-11x11-lpddr4x-frdm.conf"
GEISA_NXP_MACHINE_INCLUDE_IMX95="conf/machine/imx95-15x15-lpddr4x-frdm.conf"
GEISA_MACHINE_INCLUDE_IMX93="conf/machine/geisa-imx93-6.18.inc"
GEISA_MACHINE_INCLUDE_IMX95="conf/machine/geisa-imx95-6.18.inc"
KERNEL_VERSION="6.18.2"
KERNEL_SRCREV="f49f45233f7b10006ce7e9c826ee882bb14ac8b5"
UBOOT_VERSION="2025.04"
UBOOT_SRCREV="99518e6b6f20cb6a2bf19115e355db9f58100af8"
SOURCE_BASE="e2b65583ca857eed5d7aa675a77712fa58096bb0"
SOURCE_BITBAKE="6e511d035a3d1e4129dab7b0dfbf216bd8e99b47"
SOURCE_OPENEMBEDDED_CORE="9964fa3da2fa1e7243fba1a826e59f7bb1813706"
SOURCE_META_YOCTO="d02d3faaf4d6075ea03e9eb47654ec7639f929a0"
SOURCE_META_ARM="3752c4e4478a6dbdf7a722a261d16ebc7a4a99e5"
SOURCE_META_FREESCALE="2781242e499e601ef9454009aceed16186a48d9e"
SOURCE_META_FREESCALE_DISTRO="8001652aa3e2c6436c2bfce744e99f398c680858"
SOURCE_META_FREESCALE_ML="b364d313706d247fadf12feb68136559d7ff3d52"
SOURCE_META_IMX="fb0e606e90fbaecc273b832a9965bfef9f8b0b91"
SOURCE_META_OPENEMBEDDED="a4e768dcfae181dd99e39c4286fa0729ca7f4e47"
SOURCE_META_VIRTUALIZATION="b9a29d2423407c1e50f19dc3f3e154d164c5f0ec"
SOURCE_META_CLANG="cf20f8bd1366d41094c945597b95dd746e87b871"
