# SPDX-License-Identifier: Apache-2.0
#
# Distro based on poky. Production policy is intentionally not inherited here.
require conf/distro/poky.conf

DISTRO = "geisa-dev"
DISTRO_NAME = "GEISA FRDM-i.MX93 Development Image"
DISTRO_VERSION = "1.0"

INIT_MANAGER = "systemd"
DISTRO_FEATURES:remove = "x11 wayland"
DISTRO_FEATURES:append = " virtualization"

INHERIT += "buildhistory image-buildinfo"
BUILDHISTORY_COMMIT = "1"
