# SPDX-License-Identifier: Apache-2.0
#
# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-geisa-community"
BBFILE_PATTERN_meta-geisa-community= "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-geisa-community = "60"

LAYERSERIES_COMPAT_meta-geisa-community = "scarthgap walnascar"
