RELEASE_ID="nxp-6.12.49-2.2.0"
STATUS="experimental"
NXP_BSP_VERSION="6.12.49-2.2.0"
YOCTO_SERIES="walnascar"
BUILD_DIR="build-development-nxp-6.12.49-2.2.0"
MACHINE="geisa-imx93"
DISTRO="geisa-dev"
IMAGE="geisa-dev-image"
SOURCE_IDS="poky meta-arm meta-freescale meta-freescale-distro meta-freescale-ml meta-imx meta-openembedded meta-virtualization meta-clang meta-security"
LAYER_PATHS="sources/meta-clang sources/meta-freescale-distro sources/meta-freescale-ml sources/meta-imx/meta-imx-ml sources/meta-imx/meta-imx-bsp sources/meta-imx/meta-imx-sdk sources/meta-openembedded/meta-webserver sources/meta-openembedded/meta-gnome sources/meta-openembedded/meta-filesystems sources/meta-openembedded/meta-networking sources/meta-openembedded/meta-initramfs sources/meta-openembedded/meta-oe sources/meta-openembedded/meta-xfce sources/meta-openembedded/meta-python sources/meta-openembedded/meta-multimedia sources/meta-openembedded/meta-perl sources/meta-security/meta-parsec sources/meta-virtualization"
BBMASK_PATHS="meta-geisa-community/recipes-kernel/linux/linux-imx_6\.6\.bbappend meta-geisa-community/recipes-libraries/tensorflow-lite/tensorflow-lite-host-tools_2\.16\.2\.bbappend"
GEISA_NXP_MACHINE_INCLUDE="conf/machine/imx93-11x11-lpddr4x-frdm.conf"
GEISA_MACHINE_INCLUDE="conf/machine/geisa-imx93-6.12.49.inc"
KERNEL_VERSION="6.12.49"
KERNEL_SRCREV="df24f9428e38740256a410b983003a478e72a7c0"
UBOOT_VERSION="2025.04"
UBOOT_SRCREV="4ddbad60eff308a5b356fb9ab8734ac382ddd692"
SOURCE_POKY="d0b46a6624ec9c61c47270745dd0b2d5abbe6ac1"
SOURCE_META_ARM="21894cc2ea3197e6bfc1a56d889f757a09dc8b31"
SOURCE_META_FREESCALE="3d2781ad200846183ee3f3391f49512d0ef1b529"
SOURCE_META_FREESCALE_DISTRO="b9c3536b68271c420fe5de36fc284781ceaa32ab"
SOURCE_META_FREESCALE_ML="e55df3c0f515ba62fcc2cc4c8ddee80b99706a40"
SOURCE_META_IMX="1cfbbb8f9ce1d6071775ea6083b79d98597c8206"
SOURCE_META_OPENEMBEDDED="07330a98cf93806b7a4e0170a541b94962ff3960"
SOURCE_META_VIRTUALIZATION="38008d99d5bedc7d9769b9e95e3d6019a2df1698"
SOURCE_META_CLANG="003cba92e982bdd565a6889f28799f8bba14957e"
SOURCE_META_SECURITY="1f7eeb8e84811fa79b98f236ade42dc52d44cfc6"
