RELEASE_ID="nxp-6.6.52-2.2.2"
STATUS="supported"
NXP_BSP_VERSION="6.6.52-2.2.2"
YOCTO_SERIES="scarthgap"
BUILD_DIR="build-development"
MACHINE="geisa-imx93"
DISTRO="geisa-dev"
IMAGE="geisa-dev-image"
SOURCE_IDS="poky meta-arm meta-freescale meta-imx meta-imx-frdm meta-openembedded meta-virtualization"
LAYER_PATHS="sources/meta-imx/meta-imx-ml sources/meta-imx/meta-imx-bsp sources/meta-imx-frdm/meta-imx-bsp sources/meta-imx-frdm/meta-imx-sdk sources/meta-openembedded/meta-webserver sources/meta-openembedded/meta-gnome sources/meta-openembedded/meta-filesystems sources/meta-openembedded/meta-networking sources/meta-openembedded/meta-initramfs sources/meta-openembedded/meta-oe sources/meta-openembedded/meta-xfce sources/meta-openembedded/meta-python sources/meta-openembedded/meta-multimedia sources/meta-openembedded/meta-perl sources/meta-virtualization"
BBMASK_PATHS="meta-geisa-community/recipes-kernel/linux/linux-imx_6\.12\.bbappend meta-geisa-community/recipes-bsp/u-boot/u-boot-imx_2025\.04\.bbappend"
GEISA_NXP_MACHINE_INCLUDE="conf/machine/imx93frdm.conf"
GEISA_MACHINE_INCLUDE="conf/machine/geisa-imx93-6.6.inc"
KERNEL_VERSION="6.6.52"
KERNEL_SRCREV="5a0a5e71d2bd130577c7330cbb3764c68ebcb3dc"
UBOOT_VERSION="2024.04"
UBOOT_SRCREV="ce32a3dfd3e47ac0cf339ab35a0baee5857cfbc5"
SOURCE_POKY="200d12b6a58ad961d60a7774ca0f7a9d29498724"
SOURCE_META_ARM="950a4afce46a359def2958bd9ae33fc08ff9bb0d"
SOURCE_META_FREESCALE="0627128b341cfb2bef7a0832ce8cac0ce1127f13"
SOURCE_META_IMX="e1ec1a20d573e3913f4ad90fa36546ed2bc87715"
SOURCE_META_IMX_FRDM="0391d7457a9f044f2b38ed3f91570926a669261b"
SOURCE_META_OPENEMBEDDED="72018ca1b1a471226917e8246e8bbf9a374ccf97"
SOURCE_META_VIRTUALIZATION="6f3c1d8f90947408a6587be222fec575a1ca5195"
