RELEASE_ID="nxp-6.12.34-2.1.0"
STATUS="experimental"
NXP_BSP_VERSION="6.12.34-2.1.0"
YOCTO_SERIES="walnascar"
BUILD_DIR="build-development-nxp-6.12.34-2.1.0"
MACHINE="geisa-imx93"
DISTRO="geisa-dev"
IMAGE="geisa-dev-image"
SOURCE_IDS="poky meta-arm meta-freescale meta-imx meta-openembedded meta-virtualization meta-clang meta-security"
LAYER_PATHS="sources/meta-clang sources/meta-imx/meta-imx-ml sources/meta-imx/meta-imx-bsp sources/meta-openembedded/meta-webserver sources/meta-openembedded/meta-gnome sources/meta-openembedded/meta-filesystems sources/meta-openembedded/meta-networking sources/meta-openembedded/meta-initramfs sources/meta-openembedded/meta-oe sources/meta-openembedded/meta-xfce sources/meta-openembedded/meta-python sources/meta-openembedded/meta-multimedia sources/meta-openembedded/meta-perl sources/meta-security/meta-parsec sources/meta-virtualization"
BBMASK_PATHS="meta-geisa-community/recipes-kernel/linux/linux-imx_6\.6\.bbappend meta-geisa-community/recipes-libraries/tensorflow-lite/tensorflow-lite-host-tools_2\.16\.2\.bbappend"
GEISA_NXP_MACHINE_INCLUDE="conf/machine/imx93-11x11-lpddr4x-frdm.conf"
GEISA_MACHINE_INCLUDE="conf/machine/geisa-imx93-6.12.inc"
KERNEL_VERSION="6.12.34"
KERNEL_SRCREV="be78e49cb4339fd38c9a40019df49b72fbb8bcb7"
UBOOT_VERSION="2025.04"
UBOOT_SRCREV="44898b9f3cfe5ff881c11ab1c44b714041f2b4ac"
SOURCE_POKY="b642d6a4a93a23d5b99886844ff7b224aa7e13bf"
SOURCE_META_ARM="2de04c3d31e119d4bedbea24b9c63a8c113a1ce3"
SOURCE_META_FREESCALE="167ff4ddb79299cf5477e94620a9e598659c407b"
SOURCE_META_IMX="4d4651bec66c22aa91f1f8897140e77e20773ec4"
SOURCE_META_OPENEMBEDDED="dca497d728792e3cb655c78455c2d649af312ce8"
SOURCE_META_VIRTUALIZATION="898239e810acbb7db93299f20deec8afe434f11b"
SOURCE_META_CLANG="003cba92e982bdd565a6889f28799f8bba14957e"
SOURCE_META_SECURITY="784ca4b6584101e971b2d5d76ec7b716ad1301b5"
