# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  @PLATFORM_ROOT@/sources/poky/meta \
  @PLATFORM_ROOT@/sources/poky/meta-poky \
  @PLATFORM_ROOT@/sources/poky/meta-yocto-bsp \
  @PLATFORM_ROOT@/sources/meta-arm/meta-arm-bsp \
  @PLATFORM_ROOT@/sources/meta-arm/meta-arm \
  @PLATFORM_ROOT@/sources/meta-arm/meta-arm-toolchain \
  @PLATFORM_ROOT@/sources/meta-arm/meta-arm-systemready \
  @PLATFORM_ROOT@/sources/meta-freescale \
  @PLATFORM_ROOT@/sources/meta-geisa-community \
  @PLATFORM_ROOT@/sources/meta-imx/meta-imx-ml \
  @PLATFORM_ROOT@/sources/meta-imx-frdm/meta-imx-bsp \
  @PLATFORM_ROOT@/sources/meta-imx-frdm/meta-imx-sdk \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-webserver \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-gnome \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-filesystems \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-networking \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-initramfs \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-oe \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-xfce \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-python \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-multimedia \
  @PLATFORM_ROOT@/sources/meta-openembedded/meta-perl \
  @PLATFORM_ROOT@/sources/meta-virtualization \
  "
