# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2025 Southern California Edison
#

#@TYPE: Machine
#@NAME:
#@DESCRIPTION: GEISA machine wrapper for the selected NXP FRDM release

MACHINE = "geisa-imx93"
require ${GEISA_NXP_MACHINE_INCLUDE}
require conf/machine/geisa-imx93.inc
require ${GEISA_MACHINE_INCLUDE}
PREFERRED_PROVIDER_virtual/kernel = "linux-imx"
